### ISSUE TITLE
Install broken again

### ISSUE THREAD

**Issue by scoff3r** [espebra/filebin#15]
Hi.

Tried to install newest version today but seems like install is broken again. fs.go was edited recently as far as I can see.

----

make install
rm -f templates.rice-box.go
rm -f static.rice-box.go
rice embed-go
go install -ldflags "-X \"main.buildstamp=`date -u '+%Y-%m-%d %H:%M:%S'`\" -X \"main.githash=`git rev-parse HEAD`\""
# github.com/espebra/filebin/app/backend/fs
app/backend/fs/fs.go:334: zw.RegisterCompressor undefined (type *zip.Writer has no field or method RegisterCompressor)
Makefile:25: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by espebra** [comment]
Hi,

Master is working fine on my end, and it is currently running on https://filebin.net/. The build log is available in [travis](https://travis-ci.org/espebra/filebin).

Are you using Go 1.6 or newer? I'll make sure to update the docs with this requirement.

**Comment by scoff3r** [comment]
Gosh, sorry my mistake. Had golang 1.3 and 1.6 installed at the same time :|

**Comment by scoff3r** [comment]
Still a no go..

go build github.com/espebra/filebin: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
Makefile:25: recipe for target 'install' failed
make: *** [install] Error 1

This time I made sure it's with golang 1.6

**Comment by espebra** [comment]
Hi,

This looks similar to #12. As I wrote in #12, I suspect that you have cruft in the pkg directory which are coming from attempting to build with <1.6. After the upgrade to 1.6, you need to re-build the dependencies used by filebin. I'm not sure how to force a complete rebuild of the tree, but removing the entire pkg directory or just the relevant directories before doing ``make install`` should do it. Can you please try to do this and report back? Thanks.

**Comment by scoff3r** [comment]
Hi.

Thanks for suggestion, but I did rebuild dependencies. Actually I deleted everything and redownloaded, rebuild and re-ran make install, so basically I started from scratch.

**Comment by espebra** [comment]
I don't think your problem is related to #12 after all. My new hypothesis is that you run out of memory when building. This should be logged, so you might find traces of this in dmesg. Can you please try to increase the memory in the host or add/increase swap and try building again?

By the way, I just pushed a change (86b76d8619070cb0cd770fca1479f15f0bccfe51) that will make filebin compatible with Go 1.4 again. It is unrelated to your issue though.

**Comment by scoff3r** [comment]
Good idea, I'll double the RAM and try again.

**Comment by espebra** [comment]
I just tested this in Vagrant with a CentOS 7 with Go 1.4, 512 MB of memory and 1 GB of swap:

```
go build github.com/espebra/filebin: /usr/lib/golang/pkg/tool/linux_amd64/6g: signal: killed
make: *** [install] Error 1
```

``dmesg`` says:

```
[  177.807936] Out of memory: Kill process 4723 (6g) score 897 or sacrifice child
[  177.808309] Killed process 4723 (6g) total-vm:1440552kB, anon-rss:446324kB, file-rss:4kB
```

When bumping the memory to 8 GB (and still 1 GB of swap) it works. I'm not sure what the exact requirements are.

Also, Go 1.4 complains about the parameters ``-ldflags "-X \"main.buildstamp=${TIME}\" -X \"main.githash=${HASH}\""`` to ``go install`` in ``Makefile``. It works if you remove these or just run ``go install`` instead of ``make install``. I'm not sure how to handle this properly without looking into it more.

If you just want to build filebin without doing any local modifications, you may as well fetch the latest linux64 binary which is built by travis on each commit. It is uploaded automatically to [https://filebin.net/filebin-ci/](https://filebin.net/filebin-ci/). Please verify that the SHA256 checksum is similar to the checksum reported by the ``after_success`` script in [the latest travis job](https://travis-ci.org/espebra/filebin) before using it.

**Comment by espebra** [comment]
Hi @scoff3r,
Did you have the chance to test with more memory yet? Any success?

**Comment by scoff3r** [comment]
Just got it working :)
I tested with various RAM amounts just to find out requirements.
My original server had 0,5GB RAM and actually even 2GB wasn't enough. 1GB got to same point as 0,5GB, 2GB got little bit further but still crashed. 4GB RAM was enough to get everything done.

Thank you for the help, I'll put the software in use right away. Much better alternative to sending files by email 👍

**Comment by espebra** [comment]
Thank you for the update, I'm glad you figured it out! Although *building* the daemon requires a lot of memory, *running* it requires a lot less :)

**Comment by aslmx** [comment]
Not sure if i should raise a new issue or not... i'll try to comment here, hoping that people will find it...

make install

failed for me as well, with golang-1.10. I installed the package "golang-rice" and after that, it worked without any issues... 

Maybe that helps someone like me who is unfamilar with go :)
